version: '3.8'

services:
  # Сервис базы данных
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5433:5432" # Проект ищет порт 5433
    networks:
      - timetable_net

  # Сервис кэша
  redis:
    image: redis:7-alpine
    container_name: redis_cache
    command: redis-server --requirepass secret
    ports:
      - "6379:6379"
    networks:
      - timetable_net

networks:
  timetable_net:
    driver: bridge