spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: wiut00019278@gmail.com
    password: evqpwkqhedkpoczt
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/timetable_db
    username: postgres
    password: secret
    hikari:
      connection-init-sql: CREATE SCHEMA IF NOT EXISTS timetable

  liquibase:
    change-log: classpath:db.migration/db.changelog-master.yaml
    enabled: true

  cache:
    type: redis

  data:
    redis:
      host: redis
      port: 6379
      password: M1msoFt