spring:
  profiles:
    active: local

server:
  forward-headers-strategy: framework
  servlet:
    contextPath: /
    multipart:
      max-file-size: 16MB
  error:
    whitelabel:
      enabled: false

springdoc:
  api-docs:
    path: /api/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

info:
  app:
    name: ${spring.application.name}
    version: "@application.version@"
    description: "@application.description@"